name: _
publish_to: none
environment:
  sdk: ^3.10.0
workspace:
  - packages/solid_generator
  - packages/solid_annotations
  - packages/integration_tests
  - example
  - examples/todos
  - examples/solidart_example
  - examples/weather
  - examples/chat

dev_dependencies:
  very_good_analysis: ^10.3.0
