name: solid_generator
description: The Solid transpiler to generate fine-grained reactivity in Flutter applications.
version: 1.0.3
homepage: https://solid.mariuti.com
repository: https://github.com/nank1ro/solid
documentation: https://solid.mariuti.com
topics:
  - framework
  - zero-boilerplate
  - fine-grained-reactivity
  - swiftui
  - solidjs

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  analyzer: ^8.0.0
  args: ^2.7.0
  build: ^4.0.2
  build_runner: ^2.10.1
  crypto: ^3.0.6
  path: ^1.9.1
  source_gen: ^4.0.2

dev_dependencies:
  build_test: ^3.5.1
  lints: ^6.0.0
  test: ^1.25.6

executables:
  solid: solid_generator

builders:
  solid_builder:
    import: "package:solid_generator/builder.dart"
    builder_factories: ["solidBuilder"]
    build_extensions: {".dart": [".solid.dart"]}
    auto_apply: dependents
    build_to: source
