name: solid_annotations
description: Annotations for the solid transpiler to enable fine-grained reactivity in Flutter applications.
version: 1.0.0
homepage: https://solid.mariuti.com
repository: https://github.com/nank1ro/solid
documentation: https://solid.mariuti.com
topics:
  - framework
  - zero-boilerplate
  - fine-grained-reactivity
  - swiftui
  - solidjs

environment:
  sdk: ^3.9.2
  
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  very_good_analysis: ^10.0.0
