name: solid_annotations
description: Annotations for the solid Flutter code transformer
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.2
  
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  very_good_analysis: ^10.0.0
